// <auto-generated />
using System;
using EDU_TEST.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EDU_TEST.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260225170047_AddAdminUser")]
    partial class AddAdminUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EDU_TEST.Models.AnswerOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("AnswerOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCorrect = true,
                            QuestionId = 1,
                            Text = "Париж"
                        },
                        new
                        {
                            Id = 2,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "Ліон"
                        },
                        new
                        {
                            Id = 3,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "Марсель"
                        },
                        new
                        {
                            Id = 4,
                            IsCorrect = true,
                            QuestionId = 2,
                            Text = "Рим"
                        },
                        new
                        {
                            Id = 5,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "Мілан"
                        },
                        new
                        {
                            Id = 6,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "Неаполь"
                        },
                        new
                        {
                            Id = 7,
                            IsCorrect = true,
                            QuestionId = 3,
                            Text = "30"
                        },
                        new
                        {
                            Id = 8,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "25"
                        },
                        new
                        {
                            Id = 9,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "35"
                        },
                        new
                        {
                            Id = 10,
                            IsCorrect = true,
                            QuestionId = 4,
                            Text = "20"
                        },
                        new
                        {
                            Id = 11,
                            IsCorrect = false,
                            QuestionId = 4,
                            Text = "18"
                        },
                        new
                        {
                            Id = 12,
                            IsCorrect = false,
                            QuestionId = 4,
                            Text = "22"
                        },
                        new
                        {
                            Id = 13,
                            IsCorrect = true,
                            QuestionId = 5,
                            Text = "Володимир Великий"
                        },
                        new
                        {
                            Id = 14,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "Ярослав Мудрий"
                        },
                        new
                        {
                            Id = 15,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "Святослав"
                        },
                        new
                        {
                            Id = 16,
                            IsCorrect = true,
                            QuestionId = 6,
                            Text = "Common Language Runtime"
                        },
                        new
                        {
                            Id = 17,
                            IsCorrect = false,
                            QuestionId = 6,
                            Text = ".NET Compiler"
                        },
                        new
                        {
                            Id = 18,
                            IsCorrect = false,
                            QuestionId = 6,
                            Text = "Virtual Machine"
                        });
                });

            modelBuilder.Entity("EDU_TEST.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorrectAnswer = "Париж",
                            TestId = 1,
                            Text = "Столиця Франції?"
                        },
                        new
                        {
                            Id = 2,
                            CorrectAnswer = "Рим",
                            TestId = 1,
                            Text = "Столиця Італії?"
                        },
                        new
                        {
                            Id = 3,
                            CorrectAnswer = "30",
                            TestId = 2,
                            Text = "5 × 6 = ?"
                        },
                        new
                        {
                            Id = 4,
                            CorrectAnswer = "20",
                            TestId = 2,
                            Text = "12 + 8 = ?"
                        },
                        new
                        {
                            Id = 5,
                            CorrectAnswer = "Володимир Великий",
                            TestId = 3,
                            Text = "Хто був князем Київської Русі?"
                        },
                        new
                        {
                            Id = 6,
                            CorrectAnswer = "Common Language Runtime",
                            TestId = 4,
                            Text = "Що таке CLR у .NET?"
                        });
                });

            modelBuilder.Entity("EDU_TEST.Models.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Tests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Географія"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Математика"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Історія"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Інформатика"
                        });
                });

            modelBuilder.Entity("EDU_TEST.Models.TestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTaken")
                        .HasColumnType("datetime2");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TestId");

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("EDU_TEST.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 25, 17, 0, 45, 768, DateTimeKind.Utc).AddTicks(7774),
                            Email = "ivan@test.com",
                            FirstName = "Іван",
                            LastName = "Петренко",
                            PasswordHash = "hash1",
                            Role = "Student"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 25, 17, 0, 45, 768, DateTimeKind.Utc).AddTicks(7777),
                            Email = "maria@test.com",
                            FirstName = "Марія",
                            LastName = "Коваль",
                            PasswordHash = "hash2",
                            Role = "Student"
                        });
                });

            modelBuilder.Entity("EDU_TEST.Models.AnswerOption", b =>
                {
                    b.HasOne("EDU_TEST.Models.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("EDU_TEST.Models.Question", b =>
                {
                    b.HasOne("EDU_TEST.Models.Test", "Test")
                        .WithMany("Questions")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("EDU_TEST.Models.TestResult", b =>
                {
                    b.HasOne("EDU_TEST.Models.User", "Student")
                        .WithMany("TestResults")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EDU_TEST.Models.Test", "Test")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("EDU_TEST.Models.Question", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("EDU_TEST.Models.Test", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("EDU_TEST.Models.User", b =>
                {
                    b.Navigation("TestResults");
                });
#pragma warning restore 612, 618
        }
    }
}
